# Generated by Django 6.0.2 on 2026-02-20 05:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Número de factura')),
                ('periodo', models.CharField(help_text='Formato: MM/YYYY', max_length=7, verbose_name='Período (MM/YYYY)')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('lectura_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lectura anterior (m³)')),
                ('lectura_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lectura actual (m³)')),
                ('consumo_m3', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Consumo (m³)')),
                ('cargo_fijo', models.DecimalField(decimal_places=2, default=25.0, max_digits=10, verbose_name='Cargo fijo (S/)')),
                ('cargo_consumo', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Cargo por consumo (S/)')),
                ('cargo_alcantarillado', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='Cargo por alcantarillado (S/)')),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Monto total (S/)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^[0-9]+$', 'Solo números permitidos')], verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator('^[0-9]+$', 'Solo números permitidos')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector')),
                ('tipo_usuario', models.CharField(choices=[('VECINO', 'Vecino'), ('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('TECNICO', 'Técnico')], default='VECINO', max_length=20, verbose_name='Tipo de usuario')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la notificación')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('PAGO', 'Pago realizado'), ('CORTE', 'Corte programado'), ('RECORDATORIO', 'Recordatorio de pago'), ('COMUNICADO', 'Comunicado general'), ('RECLAMO', 'Actualización de reclamo'), ('FACTURA', 'Nueva factura')], max_length=20, verbose_name='Tipo de notificación')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado (S/)')),
                ('metodo_pago', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('EFECTIVO', 'Efectivo')], max_length=20, verbose_name='Método de pago')),
                ('codigo_operacion', models.CharField(help_text='Código de Yape, Plin o transferencia', max_length=100, verbose_name='Código de operación')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('estado_comprobante', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del comprobante')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.factura', verbose_name='Factura asociada')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('numero_medidor', models.CharField(max_length=20, unique=True)),
                ('tipo_propiedad', models.CharField(choices=[('DOMESTICO', 'Doméstico'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial')], default='DOMESTICO', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CORTADO', 'Cortado'), ('MOROSO', 'Moroso'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'propiedades',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='api.propiedad', verbose_name='Propiedad'),
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FUGA', 'Fuga de agua'), ('CALIDAD_AGUA', 'Calidad del agua'), ('MEDIDOR', 'Problema con medidor'), ('FACTURACION', 'Problema de facturación'), ('CORTE', 'Corte de servicio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de reclamo')),
                ('descripcion', models.TextField(help_text='Describa detalladamente el problema', verbose_name='Descripción del problema')),
                ('foto_url', models.URLField(blank=True, help_text='Foto del problema (opcional)', null=True, verbose_name='URL de foto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('respuesta', models.TextField(blank=True, help_text='Respuesta del personal de JASS', null=True, verbose_name='Respuesta de JASS')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='api.propiedad', verbose_name='Propiedad afectada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'db_table': 'reclamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['dni'], name='usuarios_dni_5caf68_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_usuario'], name='usuarios_tipo_us_3a6d09_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_ef49b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_24f290_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo'], name='notificacio_tipo_f5d897_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='pagos_fecha_p_8536b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['factura', 'estado_comprobante'], name='pagos_factura_d68f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['codigo_operacion'], name='pagos_codigo__4421f0_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['propiedad', 'periodo'], name='facturas_propied_f73eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_vencimiento', 'estado'], name='facturas_fecha_v_6a7e14_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='facturas_numero__52cd80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('propiedad', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='reclamo',
            index=models.Index(fields=['usuario', 'estado'], name='reclamos_usuario_9f8dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamo',
            index=models.Index(fields=['fecha_creacion'], name='reclamos_fecha_c_0d79ff_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamo',
            index=models.Index(fields=['tipo'], name='reclamos_tipo_66a0f4_idx'),
        ),
    ]
